### ISSUE TITLE
i am getting a php issue 

### ISSUE THREAD

**Issue by arcadejackpotmaster** [AndyRixon/FiveM-CAD#1]
client 76.182.13.170:55802] mod_fcgid: stderr: PHP Fatal error: require(): Failed opening required '/home/httpdocs/cad/steamauth/steamauth.php' (include_path='.:/opt/plesk/php/7.2/share/pear') in /var/www/vhosts/westcoastcaliforniaroleplay.com/httpdocs/cad/index.php on line 3,

**Comment by AndyRixon** [comment]
Could you check if the file actually exists.

**Comment by AndyRixon** [comment]
Also ensure you have set the correct path in $config['systempath'] in config.php

**Comment by arcadejackpotmaster** [comment]
---  REMOVED AS CONTAINS SENSITIVE INFORMATION ---

**Comment by AndyRixon** [comment]
Looking at your error, I think your systempath should actually be...

/var/www/vhosts/westcoastcaliforniaroleplay.com/httpdocs/cad

Give that a try and let me know.

**Comment by arcadejackpotmaster** [comment]
it worked but the UI is messed up I think https://westcoastcaliforniaroleplay.com/cad/index.php can you look and help me fix it

**Comment by AndyRixon** [comment]
Can you replace systemurl in config.php to the following:

https://westcoastcaliforniaroleplay.com/cad

**Comment by arcadejackpotmaster** [comment]
now i am getting a HTTP error

**Comment by AndyRixon** [comment]
Could you show me the entire line with the systemurl please.

**Comment by arcadejackpotmaster** [comment]
I sorry me being stupid deleted a '

**Comment by arcadejackpotmaster** [comment]
the up it still a bit wired in my opinion

**Comment by AndyRixon** [comment]
Just checked your site, you need to include https://... replace the entire line with this:

`$config['systemurl'] = 'https://westcoastcaliforniaroleplay.com/cad';`

**Comment by arcadejackpotmaster** [comment]
its working thanks how do i set myself as an admin or cop or whatever in the cad

**Comment by AndyRixon** [comment]
Theres no Admin Panel on the CAD. This is being worked on.

When you 'Sign in with Steam' there is an option that appears on the right hand side to request police permissions. If you require any other permissions that the system is currently capable of (Although the system changes these automatically when you become a cop, or remove it). This would require a manual change in the database, with either of the following IDs;

```
// Usergroup IDs
$config['banned'] = '0';
$config['police'] = '2';
$config['civ'] = '1';
```

**Comment by arcadejackpotmaster** [comment]
I changed the logo and whenever to my community but I can't figure out my the default logo is still showing,

**Comment by arcadejackpotmaster** [comment]
thanks for all the help

**Comment by AndyRixon** [comment]
I have just done a hard refresh (CTRL + F5), the new logo shows. Although you need to adjust the image size. You'll see why when you do a hard refresh.

**Comment by AndyRixon** [comment]
Your welcome for the help, anytime!

Suggested image size

Height: 185px
Width: 70px
